// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHF8Ap-XfQuJz7_yJI3H7wtKkDc0bXa2c',
    appId: '1:436572774809:web:c8650a304c407b82f2f308',
    messagingSenderId: '436572774809',
    projectId: 'silenceishearable-53e8b',
    authDomain: 'silenceishearable-53e8b.firebaseapp.com',
    storageBucket: 'silenceishearable-53e8b.appspot.com',
    measurementId: 'G-G3GB1C852M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVUaefR7TtJlvxppTJaAhZjDtZFVw-58',
    appId: '1:436572774809:android:3c933dfc0a6c2204f2f308',
    messagingSenderId: '436572774809',
    projectId: 'silenceishearable-53e8b',
    storageBucket: 'silenceishearable-53e8b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHF8Ap-XfQuJz7_yJI3H7wtKkDc0bXa2c',
    appId: '1:436572774809:web:1e10058dd3c77e6ff2f308',
    messagingSenderId: '436572774809',
    projectId: 'silenceishearable-53e8b',
    authDomain: 'silenceishearable-53e8b.firebaseapp.com',
    storageBucket: 'silenceishearable-53e8b.appspot.com',
    measurementId: 'G-44RTY44M92',
  );
}
